server:
  port: 9090

spring:
  application:
    name: Test
  servlet:
    context-path: /
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
  rabbitmq:
    host: localhost
    port: 5672
    username : guest
    password : guest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/ihiot
    username: ihiot
    password: 'ihiotGogo12@!'
    hikari:
      pool-name: idpPool
      maximum-pool-size: 20
      minimum-idle: 0
      idle-timeout: 30000
      connection-timeout: 5000
      auto-commit: false
      read-only: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
